/*
 * Auto-generated ESP32 code
 * Generated by Atech Hardware Platform
 * Using athera module drivers with FreeRTOS tasks
 */

// ========== INCLUDES ==========
#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_task_wdt.h"
#include "esp_system.h"
#include <Preferences.h>
#include "modules/shared/atech_helpers.h"
#include "modules/shared/atech_ui.h"
#include "modules/connectivity/serial_templates.h"
#include "modules/input/rotary_encoder.h"
#include "modules/display/st7735_tft.h"
// EMBEDDED_SOUNDS_FP: none
#include <ArduinoJson.h>

// ========== FREERTOS TASK HANDLES ==========
TaskHandle_t mainTaskHandle = NULL;

// ========== GLOBAL VARIABLES ==========
// ========== USB-SERIAL TRANSPORT ==========
AtechSerial wifi(115200);

// ========== MODULE INSTANCES ==========
// Rotary Encoder Knob
// Pins swapped for left-side placement: port_2 pins first, port_1 pins second
RotaryEncoder rotary_encoder_1(5, 4, 9, 8);
ST7735_TFT st7735_tft_1(2, 41, 1, 40);


// User behavior variables and helper functions
int32_t lastKnobPos = 0;
int switchCount = 0;
unsigned long lastSwitchMs = 0;
unsigned long lastCommitMs = 0;

#define UI_BG     ST7735_TFT::COLOR_BLACK
#define UI_LABEL  ST7735_TFT::COLOR_WHITE
#define UI_HEART  ST7735_TFT::COLOR_RED

bool heartPumping = false;
unsigned long heartPumpStartMs = 0;
const unsigned long HEART_PUMP_MS = 180;
unsigned long lastRenderMs = 0;

#define UI_POKE ST7735_TFT::COLOR_YELLOW
int16_t pokeX = 60;
int16_t lastPokeX = 60;
const int16_t POKE_SIZE = 14;
const int16_t POKE_STEP = 8;

void drawHeart(int16_t cx, int16_t cy, int16_t r) {
  st7735_tft_1.fillCircle(cx - r / 2, cy - r / 3, r / 2, UI_HEART);
  st7735_tft_1.fillCircle(cx + r / 2, cy - r / 3, r / 2, UI_HEART);
  st7735_tft_1.fillTriangle(cx - r, cy - r / 4, cx + r, cy - r / 4, cx, cy + r, UI_HEART);
}

void drawPokemon(int16_t x, int16_t y) {
  st7735_tft_1.fillRect(x, y, POKE_SIZE, POKE_SIZE, UI_POKE);
  st7735_tft_1.fillCircle(x + 3, y + 4, 2, UI_BG);
  st7735_tft_1.fillCircle(x + POKE_SIZE - 3, y + 4, 2, UI_BG);
  st7735_tft_1.fillRect(x + 2, y + POKE_SIZE - 3, 3, 3, UI_BG);
  st7735_tft_1.fillRect(x + POKE_SIZE - 5, y + POKE_SIZE - 3, 3, 3, UI_BG);
}

void drawScene() {
  int16_t baseR = 12;
  int16_t r = baseR;
  if (heartPumping) {
    unsigned long elapsed = millis() - heartPumpStartMs;
    if (elapsed >= HEART_PUMP_MS) {
      heartPumping = false;
    } else {
      float t = (float)elapsed / (float)HEART_PUMP_MS;
      float scale = 1.0f + 0.5f * (1.0f - fabsf(2.0f * t - 1.0f));
      r = (int16_t)(baseR * scale);
    }
  }
  st7735_tft_1.clear();
  st7735_tft_1.setFont(NULL);
  st7735_tft_1.setTextColor(UI_LABEL);
  st7735_tft_1.setTextSize(2);
  st7735_tft_1.setCursor(8, 30);
  st7735_tft_1.print("Antonia");
  drawHeart(130, 34, r);
  st7735_tft_1.fillRect(lastPokeX, 55, POKE_SIZE, POKE_SIZE, UI_BG);
  drawPokemon(pokeX, 55);
  lastPokeX = pokeX;
  st7735_tft_1.display();
}

void handleMessage(const char* action, const char* value) {
  if (strcmp(action, "set_ring_color") == 0) {
    JsonDocument d;
    if (deserializeJson(d, value) != DeserializationError::Ok) return;
    if (!d.is<JsonObject>()) return;
    if (!d["r"].is<int>() || !d["g"].is<int>() || !d["b"].is<int>()) return;
    int r = d["r"], g = d["g"], b = d["b"];
    if (r < 0 || r > 255 || g < 0 || g > 255 || b < 0 || b > 255) return;
    rotary_encoder_1.setRingColor((uint8_t)r, (uint8_t)g, (uint8_t)b);
  } else if (strcmp(action, "set_ring_brightness") == 0) {
    int v = atoi(value);
    if (v < 0 || v > 255) return;
    rotary_encoder_1.setRingBrightness((uint8_t)v);
  } else if (strcmp(action, "reset_count") == 0) {
    switchCount = 0;
    rotary_encoder_1.resetPosition();
    lastKnobPos = 0;
  }
}

// ========== MAIN TASK (runs on Core 1) ==========
void mainTask(void* parameter) {
  esp_task_wdt_add(NULL);  // Subscribe to task watchdog (30s timeout)
  uint32_t _lastHeapLog = 0;
  // Task runs forever
  while (true) {
    esp_task_wdt_reset();
    uint32_t _nowMs = millis();
    if (_nowMs - _lastHeapLog > 30000) {
      _lastHeapLog = _nowMs;
      Serial.printf("[Atech heap] free=%u min=%u\n", (unsigned)ESP.getFreeHeap(), (unsigned)ESP.getMinFreeHeap());
    }
        // ========== USER BEHAVIOR ==========
        rotary_encoder_1.update();
        wifi.maintain();

        int32_t pos = rotary_encoder_1.getPosition();
        int _priorSwitchCount = switchCount;
        for (; lastKnobPos < pos; lastKnobPos++) {
        switchCount++;
        wifi.postButtonEvent("switch_next", 1);
        pokeX += POKE_STEP;
        if (pokeX > st7735_tft_1.width() - POKE_SIZE) pokeX = 0;
        }
        for (; lastKnobPos > pos; lastKnobPos--) {
        switchCount++;
        wifi.postButtonEvent("switch_prev", 1);
        pokeX -= POKE_STEP;
        if (pokeX < 0) pokeX = st7735_tft_1.width() - POKE_SIZE;
        }
        if (switchCount != _priorSwitchCount) {
        lastSwitchMs = millis();
        heartPumping = true;
        heartPumpStartMs = lastSwitchMs;
        }

        if (rotary_encoder_1.wasPressed()) {
        wifi.postButtonEvent("knob_press", 1);
        }

        if (millis() - lastRenderMs >= 16) {
        lastRenderMs = millis();
        drawScene();
        }
  }
}

// ========== SETUP ==========
void setup() {
  Serial.setRxBufferSize(8192);
  Serial.begin(115200);
  Serial.setTxTimeoutMs(0);
  Serial.println("Initializing...");

  // ========== BOOT DIAGNOSTICS ==========
  {
    Preferences _bootPrefs;
    _bootPrefs.begin("atech_boot", false);
    uint32_t _bootCount = _bootPrefs.getUInt("count", 0) + 1;
    _bootPrefs.putUInt("count", _bootCount);
    _bootPrefs.end();

    esp_reset_reason_t _reason = esp_reset_reason();
    const char* _reasonStr = "UNKNOWN";
    switch (_reason) {
      case ESP_RST_POWERON:   _reasonStr = "POWERON";   break;
      case ESP_RST_EXT:       _reasonStr = "EXT_PIN";   break;
      case ESP_RST_SW:        _reasonStr = "SOFTWARE";  break;
      case ESP_RST_PANIC:     _reasonStr = "PANIC";     break;
      case ESP_RST_INT_WDT:   _reasonStr = "INT_WDT";   break;
      case ESP_RST_TASK_WDT:  _reasonStr = "TASK_WDT";  break;
      case ESP_RST_WDT:       _reasonStr = "OTHER_WDT"; break;
      case ESP_RST_DEEPSLEEP: _reasonStr = "DEEPSLEEP"; break;
      case ESP_RST_BROWNOUT:  _reasonStr = "BROWNOUT";  break;
      case ESP_RST_SDIO:      _reasonStr = "SDIO";      break;
      default: break;
    }

    Serial.println();
    Serial.println("================ ATECH BOOT ================");
    Serial.printf("  Boot count : %u\n", _bootCount);
    Serial.printf("  Reset cause: %s (%d)\n", _reasonStr, (int)_reason);
    Serial.printf("  Free heap  : %u bytes\n", (unsigned)ESP.getFreeHeap());
    Serial.printf("  Min heap   : %u bytes (lowest since boot)\n", (unsigned)ESP.getMinFreeHeap());
    Serial.printf("  CPU freq   : %u MHz\n", (unsigned)ESP.getCpuFreqMHz());
    Serial.println("============================================");
  }

  // Initialize modules
  rotary_encoder_1.begin();
  st7735_tft_1.begin();

  // ========== USB-SERIAL TRANSPORT ==========
  wifi.connect();  // Serial.begin(115200) — always succeeds
  Serial.println("[Atech] Transport: USB-Serial");

  Serial.println("Setup complete!");

  // ========== USER BEHAVIOR SETUP ==========
  rotary_encoder_1.setAcceleration(false, 5);
  lastKnobPos = rotary_encoder_1.getPosition();
  rotary_encoder_1.enableRing(true);
  rotary_encoder_1.setRingColor(0, 200, 255);
  rotary_encoder_1.setRingBrightness(80);
  wifi.onMessage(handleMessage);
  drawScene();

  // ========== TASK WATCHDOG ==========
  esp_task_wdt_init(30, true);  // 30s timeout, panic on trigger

  // ========== CREATE FREERTOS TASKS ==========
  // Create main task on Core 1 (Core 0 is used by WiFi/BT)
  xTaskCreatePinnedToCore(
    mainTask,           // Task function
    "MainTask",         // Task name
    16384,              // Stack size (bytes) - 16KB for HTTPS/TLS
    NULL,               // Parameters
    1,                  // Priority (1 = low, higher = more priority)
    &mainTaskHandle,    // Task handle
    1                   // Core ID (0 or 1)
  );

  Serial.println("FreeRTOS tasks started!");
}

// ========== MAIN LOOP (empty - tasks handle everything) ==========
void loop() {
  // Nothing here - FreeRTOS tasks handle all operations
  // This allows other tasks and system processes to run
  vTaskDelay(portMAX_DELAY);
}